# Generated by Django 5.2.8 on 2025-11-10 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post_recommendations',
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['user', '-score'], name='post_recomm_user_id_40d1d5_idx')],
                'unique_together': {('user', 'post')},
            },
        ),
    ]
